#!/bin/sh
set -eu
IFS="$(printf '%b_' '\n\t ')"
IFS="${IFS%_}"

sudo yum update -y &&
    sudo yum groupinstall -y 'Development Tools' &&
    sudo yum install -y \
        libstdc++-static \
        compat-libstdc++-33
